service: admin-api
frameworkVersion: ^2.52.0
configValidationMode: off

provider:
  name: kubeless
  runtime: nodejs14
  timeout: 360
  namespace: ${opt:namespace, 'default'}

plugins:
  - serverless-kubeless

functions:
  admin-api--list-user:
    handler: listUsers.handler
    description: "list all users"
  admin-api--create-user:
    handler: createUser.handler
    description: "create new user"
